ory/kratos-selfservice-ui-node

src/index.ts
views/dashboard.hbs

add dashboard and redirect to it on any other route

read HIVE_PUBLIC_URL from env

---

src/routes/auth.ts
src/translations.ts
views/partials/buttonFormInput.hbs
views/registration.hbs

fix: improve oidc ui elements

---

src/index.ts

Related to, but **does not fix** #44 
'request' module specific error handler, see examples from its docs here - https://www.npmjs.com/package/request#streaming
the changes.

fix: error handler for 'request' module - refs #44

---

package-lock.json
package.json
src/routes/auth.ts
src/routes/settings.ts
src/routes/verification.ts
views/login.hbs
views/partials/form.hbs
views/partials/form_errors.hbs
views/partials/form_input_default.hbs
views/partials/form_input_password.hbs
views/partials/form_messages.hbs
views/partials/messages.hbs
views/recovery.hbs
views/registration.hbs
views/settings.hbs
views/verification.hbs

See https://github.com/ory/kratos/pull/476
See https://github.com/ory/kratos/pull/428
See https://github.com/ory/kratos/issues/37
the changes.

refactor: use messages instead of errors

---

package-lock.json
package.json
src/routes/settings.ts
views/settings.hbs

fix: use new settings state

---

.circleci/config.yml
src/routes/recovery.ts

fix: rename token to recovery_token

---

src/routes/recovery.ts

fix: rename recovery to link

---

src/routes/recovery.ts
views/login.hbs

feat: add recovery link to login page and use link method

---

src/routes/recovery.ts
src/routes/settings.ts
views/login.hbs
views/recovery.hbs
views/settings.hbs

Add recovery link

---

README.md

fix: correct typos in readme.md

---

package-lock.json
package.json

chore: bump kratos sdk

---

README.md
src/config.ts
src/index.ts

#62 
Adds optional TLS_CERT_PATH and TLS_KEY_PATH variables that enable https
the changes.

feat: Implemented HTTPS support configured using env vars

---

src/helpers.ts
src/routes/auth.ts
src/routes/error.ts
src/routes/recovery.ts
src/routes/settings.ts
src/routes/verification.ts

refactor: clean up typescript smells

---

package-lock.json
package.json
src/config.ts
src/index.ts
views/layouts/main.hbs

None.
String concatenation for url paths has quite a lot of downsides, including ending up with a double slash (e.g.`mypath//otherpath`) or with no trailing slash where it should be set (e.g `https://example.com/myurl` instead of `https://example.com/myurl/`).
The latest scenario makes it difficult to properly route traffic through ingresses or reverse proxies.
As an example, our current setup routes requests to `https://example.com/ui/` to the kratos selfservice application.
Unfortunately, the current implementation of the selfservice removes the trailing slash at the end, which means that `res.redirect(config.baseUrl)` (which is in multiple places in the codebase) will redirect the browser to `https://example.com/ui` and not  `https://example.com/ui/` as intended. The result is that the …

fix: Use url-join instead of string concatenation

---

README.md
package-lock.json
package.json
src/config.ts
src/index.ts
src/routes/auth.ts
src/routes/error.ts
src/routes/recovery.ts
src/routes/settings.ts
src/routes/verification.ts
views/recovery.hbs
views/verification.hbs

Update to match changes in ORY Kratos 0.5

---

src/index.ts
src/middleware/oathkeeper.ts
src/middleware/simple.ts
src/routes/login.ts
src/routes/registration.ts
src/translations.ts
views/verification.hbs

fix: improve file paths

---

.prettierrc
Dockerfile
Makefile
contrib/sdk/typescript.yml
package-lock.json
package.json
src/helpers.ts
src/middleware/simple.ts
src/routes/error.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/settings.ts
src/routes/verification.ts

refactor: move to new typescript-axios sdk

---

package-lock.json
package.json
src/helpers.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/settings.ts
src/routes/verification.ts
src/translations.ts

fix: bump sdk and refactor helpers

---

src/routes/settings.ts

fix: correct settings methods

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/closed_references.yml
.github/workflows/stale.yml
.reference-ignore
CONTRIBUTING.md
SECURITY.md

Updated repository templates to https://github.com/ory/meta/commit/bf0b087e8893145e2067664515b1a75cb45fb92e.

chore: update repository template to bf0b087e

---

contrib/sdk/typescript.yml
package-lock.json
package.json
src/routes/dashboard.ts
views/dashboard.hbs

fix: update dashboard instructions

---

README.md
package-lock.json
package.json

Update README and bump SDK

---

src/helpers/ui.ts
views/partials/ui_node_input_checkbox.hbs

the changes.
works.
appropriate).

fix: properly handle checkboxes

---

.dockerignore
Dockerfile
package-lock.json

the changes.
works.
appropriate).

fix: bump node to fix build issue

---

src/index.ts

This change is self-explanatory.

fix: populate prefixPath variable in views. Closes #119

---

openapitools.json
package-lock.json
package.json
src/index.ts
src/middleware/simple.ts
src/routes/dashboard.ts
src/routes/settings.ts
views/partials/header.hbs

the changes.
works.
appropriate).

feat: support new logout flow

---

package-lock.json
package.json
src/routes/dashboard.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/settings.ts
src/routes/verification.ts

the changes.
works.
appropriate).

feat: prepare for kratos v0.7

---

.prettierrc
package.json
src/helpers/ui.ts
src/middleware/oathkeeper.ts
src/middleware/simple.ts
src/routes/dashboard.ts
src/routes/error.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/settings.ts
src/routes/verification.ts
src/stub/payloads.ts

TS files in nested folders were ignored by prettier.
I also centralized all prettier params to `.prettierrc`.

fix(codestyle): some TS files ignored by prettier

---

Makefile
contrib/sdk/api.json
package-lock.json
package.json
src/middleware/simple.ts
src/routes/dashboard.ts
src/routes/error.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/settings.ts
src/routes/verification.ts

See https://github.com/ory/kratos/pull/1477
the changes.
works.
appropriate).

feat: use new ory kratos sdk

---

src/config.ts
src/routes/dashboard.ts
src/routes/error.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/settings.ts
src/routes/verification.ts

the changes.
works.
appropriate).

chore: clean up codebase

---

Makefile
contrib/sdk/api.json
package-lock.json
package.json
src/helpers/ui.ts
src/routes/error.ts
src/routes/login.ts
views/partials/ui_node_image.hbs
views/partials/ui_node_input_button.hbs
views/partials/ui_node_input_checkbox.hbs
views/partials/ui_node_input_default.hbs
views/partials/ui_node_input_password.hbs
views/partials/ui_node_text.hbs
views/settings.hbs

the changes.
works.
appropriate).

feat: add support for 2fa

---

src/routes/login.ts
src/routes/registration.ts

the changes.
works.
appropriate).

fix: resolve path issues

---

package.json
src/routes/login.ts
src/routes/registration.ts
views/partials/fork_me.hbs

the changes.
works.
appropriate).

Fix cloud hostedui

---

package.json
src/index.ts
src/pkg/route.ts
src/routes/welcome.ts

the changes.
works.
appropriate).

feat: improve consumability

---

README.md
src/pkg/index.ts

Closes #163
the changes.
works.
appropriate).

feat: add base url option

---

src/routes/registration.ts

the changes.
works.
appropriate).

fix: "Sign in" button wrong redirect ory#171

---

src/index.ts

- removed the second registartion of the welcome route
the changes.
works.
appropriate).

fix: remove duplicated line

---

views/partials/ui_node_input_checkbox.hbs

fix: fix a typo in ui_node_input_checkbox.hbs

---

README.md
src/pkg/index.ts
src/pkg/middleware.ts
src/pkg/route.ts

fix: respect base url

---

Makefile
contrib/sdk/typescript.yml
package-lock.json
package.json
src/pkg/middleware.ts
src/pkg/route.ts
src/pkg/sdk/index.ts
src/pkg/ui.ts

refactor: use @ory/client

---

README.md

Tests are running on GitHub Actions now.

ci: update badge from CircleCI to GitHub Actions

---

.circleci/config.yml
.github/workflows/format.yml
.github/workflows/test.yml
.prettierrc.js
Makefile
package-lock.json
package.json
src/index.ts
src/pkg/index.ts
src/pkg/middleware.ts
src/routes/500.ts
src/routes/error.ts
src/routes/health.ts
src/routes/static.ts
src/routes/welcome.ts

Addresses parts of https://github.com/ory-corp/general/issues/735.

chore: format using Make

---

src/routes/login.ts

fix: missing types

---

package-lock.json
package.json

chore: bump elements version

---

package-lock.json
public/main.css
src/pkg/route.ts
src/routes/404.ts
src/routes/500.ts
src/routes/error.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/verification.ts

fix: remove card logo and fix margins

---

package-lock.json
package.json

chore: update elements

---

.gitignore
Makefile
src/index.ts
src/pkg/index.ts
src/pkg/logger.ts
src/pkg/middleware.ts
src/pkg/route.ts
src/pkg/sdk/index.ts
src/pkg/ui.ts
src/routes/404.ts
src/routes/500.ts
src/routes/error.ts
src/routes/health.ts
src/routes/index.ts
src/routes/login.ts
src/routes/recovery.ts
src/routes/registration.ts
src/routes/sessions.ts
src/routes/settings.ts
src/routes/static.ts
src/routes/verification.ts
src/routes/welcome.ts

Add license headers clarifying the copyright of source code files.
https://github.com/ory-corp/general/issues/602

docs: standardize license headers

---

package-lock.json

chore: fix package-lock

---

src/routes/welcome.ts

fix: welcome cards text

---

src/index.ts

Tried installing opentelemetry in a fork of this, and noticed for every request, it first tried to find a matching static file.  
Like you can see in the image below:
The reason is static-file-route is being registered first on `/`, but after moving it down to right before 404, the trace looks a lot better, and the response is quicker, like seen below:

fix: stop trying to load staticfiles first

---

Makefile

fix: bump Ory CLI dependency

---

.npmignore
package.json

Ref https://github.com/ory/kratos-selfservice-ui-node/issues/239
`npm pack` reports:
```
npm notice 
npm notice 📦  @ory/kratos-selfservice-ui-node@0.11.0-alpha.2
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE                     
npm notice 3.9kB  README.md                   
npm notice 11B    lib/index.d.ts              
npm notice 3.3kB  lib/index.js                
npm notice 668B   lib/pkg/index.d.ts          
npm notice 5.0kB  lib/pkg/index.js            
npm notice 136B   lib/pkg/logger.d.ts         
npm notice 727B   lib/pkg/logger.js           
npm notice 1.1kB  lib/pkg/middleware.d.ts     
npm notice 3.2kB  lib/pkg/middleware.js       
npm notice 661B   lib/pkg/route.d.ts          
npm notice 77B    lib/pkg/route.js            
npm notice 211B …
```

fix: don't include unnecessary files in NPM package

---

package-lock.json
package.json
src/pkg/index.ts

This PR removes the unused `handlebar-helpers` package. We have moved most of the rendering tasks to `react-dom/server` inside Ory Elements and do not require `handlebar-helpers` at all.

chore: remove handlebar-helpers

---

src/routes/login.ts

fix: login should respect return_to on navigation to recovery

---

package-lock.json
package.json

Required by https://github.com/ory/kratos/pull/3067

chore: update @ory/elements to v0.0.1-beta.3

---

src/routes/welcome.ts

chore: update custom UI docs link

---

contrib/sdk/api.json
contrib/sdk/typescript.yml
src/routes/login.ts
src/routes/registration.ts

chore: sync local sdk config with ory/client config

---

src/routes/login.ts

fix: refresh login card title

---

src/pkg/index.ts
src/pkg/middleware.ts
src/routes/settings.ts

When an MFA credential is required, the user is redirected to the login page for MFA. After successful login, the user should be redirected back to the settings flow. To make this possible the UI should allow the settings flow to catch the 403 `session_aal2_required` error and redirect the browser according to the response data from Kratos (`redirect_browser_to`).
Required by  https://github.com/ory/kratos/pull/3263

fix: settings flow redirecting to mfa should continue with settings flow

---

package-lock.json
src/pkg/middleware.ts

This PR adds the current requested page as the return_to page when redirecting to login with `aal=aal2`.
This is especially true for when we want to redirect back to the original page the user was navigating to. This fixes the problem where a user has logged in and navigates directly to the settings page but still needs to complete MFA.
After completing the login flow the user is now stuck on the `/welcome` page.

fix: users should return to previous screen on mfa required

---

package-lock.json
package.json
src/pkg/index.ts

chore: bump @ory/client v1.1.39

---

.circleci/config.yml
.github/workflows/test.yml
Makefile
contrib/sdk/api.json
package-lock.json
package.json
src/routes/login.ts

feat: logout return_to at mfa

---

src/pkg/ui.ts

Closes https://github.com/ory/network/issues/226

chore: logout -> log out

---

package-lock.json
package.json
src/pkg/ui.ts

chore: bump ory/client to 1.1.40

---

src/routes/500.ts

fix: improve error message

---

src/routes/login.ts

Logout link is broken on login refresh

fix: logout on login refresh

---

package-lock.json
package.json

chore: v0.13.0-6

---

package-lock.json
package.json

chore: bump package versions

---

package-lock.json
package.json
public/auth-layout.css

fix: add error card improvements

---

package-lock.json
package.json

chore: bump @ory/elements & @ory/client

---

package-lock.json
package.json

Update package version in package.json.

chore: v0.13.0-8

---

package-lock.json
package.json

Fixes [CVE-2023-26136](https://github.com/advisories/GHSA-72xf-g2v4-qvf3) by overriding the `tough-cookie` package in the `request` package.

fix: CVE-2023-26136 `tough-cookie` package

---

views/settings.hbs

fix: wrong trigger element for settings webauthn

---

package-lock.json
package.json

Updates `@ory/elements`. 
https://github.com/ory/elements/compare/v0.1.0-beta.4...v0.1.0-beta.7
Improvements
- spanish translations fixes
- dutch translation
- swedish translation
- french translation
- hide labels of hidden input types
- fixes recovery and verification card width

chore: elements bump

---

package.json
src/routes/consent.ts

feat: convert `id_token.updated_at` to date

---

package-lock.json
package.json

Updates `@ory/elements` to 0.1.0-beta.11
Implements:
1. Input field pattern match
2. Fix password visibility toggle to not active on tab key
https://github.com/ory/elements/compare/v0.1.0-beta.9...v0.1.0-beta.11

chore: bump ory/elements 0.1.0-beta.11

---

package-lock.json
package.json

-20 was not commited apparently.

chore: bump version to v0.13.0-21

---

package-lock.json
package.json

chore: bump to 0.13.0-22

---

package-lock.json
package.json
src/routes/settings.ts

feat: add back button to selfservice settings

---

nodemon.json
src/routes/login.ts
src/routes/registration.ts
src/routes/settings.ts

Part of https://github.com/ory-corp/cloud/issues/5470

feat: passwordless strategy

---

package-lock.json
package.json
views/login.hbs
views/partials/js_setup.hbs
views/registration.hbs
views/settings.hbs

Part of https://github.com/ory-corp/cloud/issues/5470

feat: passkey support

---

package.json

chore: bump to 0.13.0-25

---

package-lock.json
package.json
src/pkg/index.ts
src/routes/login.ts
src/routes/registration.ts
src/routes/settings.ts

chore: bump deps

---

package-lock.json
package.json

chore: bump elements to 0.3.0-rc.0

---

package-lock.json
package.json

chore: bump elements to 0.3.0-rc.1

---

package-lock.json
package.json

chore: pin 0.18.0

---

package-lock.json
package.json

chore: update vulnerable dependencies

---

package-lock.json
package.json

chore: fix CVE-2024-45296

---

package-lock.json
package.json

chore: upgrade elements to 0.5.0

---

package-lock.json
package.json

chore: bump express to 4.21.2

---

package-lock.json
package.json

chore: pin 0.22.0

---

package-lock.json
package.json

chore: bump @ory/elements-markup to v0.5.1

---

package-lock.json
package.json
src/pkg/index.ts

fix: redirect to login if settings get was unauthenticated

---

package-lock.json
package.json

chore: bump axios to v1.8.2

---

views/partials/standard_headers.hbs

fix: preload fonts

---

package-lock.json
package.json

fix: upgrade client
