README.md, package-lock.json, package.json, public/index.css, src/auth.ts, src/config.ts, src/dashboard.ts, src/error.ts, views/login.hbs, views/registration.hbs
It seems this repo's name was `hive-selfservice-ui-node` and renamed `kratos-selfservice-ui-node` but source code is still old name.
I confused because I didn't know what Hive means.
=> Rename Kratos in source code

README.md, package-lock.json, package.json, src/config.ts, src/index.ts, src/routes/dashboard.ts
I struggled a lot with the full appropriate setup (without Docker). At the beginning I refused to rely on OathKeeper but I had too much trouble with invalid CSRF cookies.
I kicked ouf OathKeeper and get everything to work.
I thought it was worth giving a try to an implementation (simplification) without OathKeeper.
This proxies Kratos public API at /self-service which sound enough for an exemplary Self Service UI.
Related to https://github.com/ory/kratos/issues/262.
=> improvement: Implement a version without OathKeeper

src/config.ts, src/routes/dashboard.ts
https://github.com/ory/kratos-selfservice-ui-node/issues/58
in `dashboard.ts`
```
if (config.securityMode === config.SECURITY_MODE_JWT) {
```
in `config.ts`
```
securityMode,
SECURITY_MODE_JWT,
SECURITY_MODE_STANDALONE,
```
the changes.
=> fix: Fix 'jwt' compare bug in dashboard.ts

src/routes/hydra.ts
#67 
1. Replace 'host' header while communicating with kratos to prevent reverse-proxy misbehaviour - see #60 . Fixes 302 redirect error with Traefik. Probably with nginx there will be another error: the wrong host will respond to http query. Therefore response will obviously have unexpected content.
2. Make code read Hydra URL from config instead of reading from env var directly. As as side effect it removes trailing slash which fixes 307 redirect error while communicating with Hydra (either in domain-based env or I just have env vars misconfigured - I don't know and it dows not matter because anyway there is no need to read anything from env when we do already have everything in config)
confirm that I got green …
=> fix: redirect issues for hydra integration in domain (not port) based env

src/config.ts, src/index.ts
`urljoin` introduced with #70 actually behaves differently than expected:
```js
urljoin('', '/some-path')
// gives 'some-path'
```
=> fix: case where BASE_URL is empty

README.md
* Add the KRATOS_BROWSER_URL environment variable in the quickstart to make the ui work in development mode. Without the variable the ui tries to redirect to the kratos path but on the same site which leads to an endless redirect loop.
* Corrects the container to kill to be able to start the development ui 
the changes.
=> docs: adds missing KRATOS_BROWSER_URL env var and corrects which container to kill

.github/pull_request_template.md, CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/8042a8da0b42c9ff50deb9860249f95c756af18f.
=> chore: update repository template to 8042a8da

.github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/5a138d3599973232cc4d86812c1cf4dc6306c113.
=> chore: update repository template to 5a138d35

Dockerfile
* https://github.com/ory/hydra-login-consent-node/pull/91
As described in the linked PR for security reasons we should not run processes inside Docker container as root. This should allow us run this image safely on kubernetes with elevated Pod Security Policies. Since this is an example service not to meant to be run on production environment it is not a real security concern.
the changes.
works.
appropriate).
=> fix: do not run as root in Dockerfile

src/index.ts
Fixes issue introduced in #120.
`path.join()` does not work well with fully qualified URLs producing: `https:/example.com` instead of `https://example.com`.
the changes.
works.
appropriate).
=> fix: Properly build pathPrefix variable

Dockerfile-dev, Makefile, contrib/sdk/api.json, package-lock.json, package.json, src/pkg/ui.ts, src/routes/login.ts, src/routes/registration.ts, views/login.hbs, views/registration.hbs
This branch is based on the `fix-new-sdk` branch which was ahead of master.
=> feat: kratos hydra integration

.dockerignore
Add `.git` to `.dockerignore`, a lot more could probably be added to `.dockerignore`, but atleast `.git` should not be copied over.
Before added `.git` to `.dockerignore`:
```
at 17:39:06 ❯ docker build .
Sending build context to Docker daemon  949.8kB
Step 1/14 : FROM node:17.0-alpine
---> c0fc1c9c473b
...snipped...
Successfully built 92f2ee319e75
at 17:39:22 ❯ docker run -it --entrypoint /bin/sh  92f2ee319e75
/usr/src/app $ ls .git
.git
```
After:
```
at 17:42:39 ❯ docker build .
Sending build context to Docker daemon  948.7kB
Step 1/14 : FROM node:17.0-alpine
---> c0fc1c9c473b
...snipped...
Successfully built 5cb0247274a4
at 17:42:48 ❯ docker run -it --entrypoint /bin/sh  5cb0247274a4
/usr/src/app $ ls .git
ls: .git: No such file or directory
```
If this pull request addresses a …
=> chore: add .git to .dockerignore

src/routes/settings.ts
"requires a you to..." -> "requires you to" on the settings page
=> chore: fix a typo

package-lock.json, src/routes/login.ts
Redirecting to the `/verification` route with a base URL would cause problems since the redirect would be to the root of the URL and not the base path of the URL.
=> fix: verification redirect base url

src/routes/login.ts
=> fix: hide recovery link on refresh

src/routes/consent.ts
Add code to handle the flag skip consent from OAuth2 Client.
=> feat: use skip consent from OAuth2 client

src/pkg/index.ts
Fixes regression on https://github.com/ory/kratos-selfservice-ui-node/commit/a96574d57a050be613edeed875c30256e3829a26.
This causes incorrect error handling on recovery with mfa with return_to URL. 
=> fix: correct error checking for recovery with mfa return_to

src/routes/settings.ts, src/routes/welcome.ts
https://github.com/ory-corp/cloud/issues/3524
=> feat: settings and welcome page should support logout return_to

package-lock.json, src/routes/error.ts
Related to https://github.com/ory/network/issues/325
=> fix: show OAuth2 error details on error screen

package.json
Seems like this repo requires a type def for `body-parser` to work properly
```
$ pnpm run start
> @ory/kratos-selfservice-ui-node@0.13.0-7 start ***\ory-kratos\kratos-selfservice-ui-node
> nodemon
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src\**\*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node ./src/index.ts`
┌───────────────────────────────────┐
│ New version of nodemon available! │
│ Current Version: 2.0.20           │
│ Latest Version: 3.0.1             │
└───────────────────────────────────┘
***\ory-kratos\kratos-selfservice-ui-node\node_modules\.pnpm\ts-node@10.9.1_@types+node@18.16.19_typescript@4.9.5\node_modules\ts-node\src\index.ts:859
return new TSError(diagnosticText, diagnosticCodes, diagnostics);
^
TSError: ⨯ …
```
=> fix: fixing "Could not find a declaration file for module 'body-parser'" Error

src/index.ts, src/pkg/index.ts, src/pkg/middleware.ts, src/pkg/route.ts, src/routes/recovery.ts, views/layouts/auth.hbs, views/partials/standard_headers.hbs
=> feat: customizable favicon

src/routes/login.ts, src/routes/registration.ts
=> feat: forward org ID during login and registration

README.md, nodemon.json, package-lock.json, package.json, src/index.ts, src/pkg/index.ts, src/pkg/route.ts, src/pkg/sdk/index.ts, src/pkg/ui.ts, src/routes/consent.ts, src/routes/sessions.ts, src/routes/stub/oidc-cert.ts, types/express/index.d.ts
Replaces `csurf` with `csrf-csrf`. https://www.npmjs.com/package/csrf-csrf
I have also updated the Ory client to the latest version.
Since this is a change in security related packages concerning CSRF protection on the consent endpoint, could you take a look @hperl?
=> feat: update csurf -> csrf-csrf

src/pkg/route.ts, src/routes/login.ts, src/routes/registration.ts, views/login.hbs, views/registration.hbs
This PR allows adding a function that returns some kind of partial name via the `createHelpers` object for the login & registration routes. It also enables passing extra context via the `res.locals` object to the templates.
=> feat: allow external partials on login & registration

package-lock.json, package.json
Updates the `@ory/elements` package to `v0.1.0-beta.8`.
Adds portuguese as a new language to the UI.
Fixes the usage of existing translations such as dutch, french and swedish.  
https://github.com/ory/elements/compare/v0.1.0-beta.7...v0.1.0-beta.9
=> chore: update elements v0.1.0-beta.9

src/routes/registration.ts
When users have a session and they are redirected to the registration UI on the account experience, they will end up on the `/welcome` page. This is due to the session check happening in the Express middleware. This is incorrect behavior since the redirect to the welcome route is hard coded and not an ideal route to leave the user at. 
In OAuth flows, this is even more confusing, since the OAuth flow has its own logic when a session is present. OAuth flows usually redirect to the consent route if a session is present and there were no subject mismatches. 
This PR removes the session check middleware on the registration route and allows Kratos to handle the redirect logic for us.  
https://github.com/ory-corp/cloud/issues/5493
https://github.com/ory/kratos/pull/3592
If this pull request …
=> fix: let kratos handle session redirects

nodemon.json
Seems like adding that breaks Kratos e2e tests, somehow... This should fix the tests for now. cc @hperl
=> chore: remove PORT from nodemon envs

src/pkg/index.ts, src/pkg/route.ts, src/routes/logout.ts
=> feat: add skip logout consent option

package-lock.json, src/pkg/index.ts, src/pkg/ui_nodes.ts
Merging this will fix E2E failures on Kratos master.
=> fix: incorrect implementation of filterNodesByGroups

README.md
Add more documentation for Hydra consent flow integration.
=> docs: add KRATOS_ADMIN_URL env variable and fix HYDRA_ADMIN_URL mistake

src/pkg/middleware.ts
=> fix: return_to URL in maybeInitiate2FA

src/index.ts, views/logout.hbs
=> fix: logout functionality

nodemon.json, package-lock.json, package.json, src/index.ts, src/pkg/logger.ts, src/routes/500.ts
=> fix: logging setup and error card error display

package-lock.json, package.json, src/pkg/index.ts, src/routes/login.ts, views/partials/js_setup.hbs
=> chore: bump elements to 0.4.0
